# Generated by Django 5.0.1 on 2024-01-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('was_cooked', models.IntegerField(default=0, verbose_name='Количество использований продукта в рецептах')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рецепта')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeToProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking.productmodel', verbose_name='Объект продукта')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking.recipemodel', verbose_name='Объект рецепта')),
            ],
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='products',
            field=models.ManyToManyField(through='cooking.RecipeToProductModel', to='cooking.productmodel'),
        ),
    ]
